# Generated by Django 4.2.2 on 2023-09-04 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evento_json', models.JSONField()),
                ('motivo_alteracao', models.TextField()),
                ('tipo_projeto', models.IntegerField(choices=[('1', 'EFG'), ('2', 'COTEC'), ('3', 'CETT')])),
                ('publico_evento', models.TextField()),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[('0', 'Solicitação Criada'), ('1', 'Aguardando Entregas'), ('2', 'Concluída'), ('3', 'Devolvida')])),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitacoes',
            },
        ),
    ]
