# Generated by Django 4.2.2 on 2023-09-04 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregaveis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prazo', models.DateField()),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.now)),
                ('exemplo_arte', models.CharField(default='', max_length=255)),
                ('tipo_entregavel', models.IntegerField(choices=[('1', 'SAVE THE DATE'), ('2', 'DIVULGAÇÃO'), ('3', 'PROGRAMAÇÃO'), ('4', 'STAND')])),
                ('tipo_produto', models.IntegerField(choices=[('1', 'DIGITAL'), ('2', 'IMPRESSO'), ('3', 'AUDIOVISUAL'), ('4', 'COBERTURA DE EVENTO'), ('5', 'PRODUÇÃO DE ÁUDIO VISUAL (ORÇAMENTOS E EXECUÇÕES)')])),
                ('categoria_produto', models.CharField(default='', max_length=255)),
                ('descricao_audio_visual', models.TextField()),
                ('observacao', models.TextField()),
                ('motivo_revisao', models.TextField(default='')),
                ('status', models.IntegerField(choices=[('0', 'AGUARDANDO ENTREGAS'), ('1', 'EM APROVAÇÃO'), ('2', 'EM REVISÃO'), ('3', 'APROVADO PELO CLIENTE')], default=0)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criado_por', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'entregaveis',
            },
        ),
    ]
