# Generated by Django 4.2.2 on 2023-09-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_entregaveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao_Adicional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default='')),
                ('hora', models.CharField(default='', max_length=5)),
                ('hora_final', models.CharField(default='', max_length=5)),
                ('atividade', models.CharField(default='', max_length=100)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'programacao_adicional',
            },
        ),
    ]
