# Generated by Django 4.2.2 on 2023-09-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_alter_programacao_adicional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitação Criada'), (2, 'Aguardando Entregas'), (3, 'Concluída'), (4, 'Devolvida')], default=2),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='tipo_projeto',
            field=models.IntegerField(choices=[(1, 'EFG'), (2, 'COTEC'), (3, 'CETT')]),
        ),
    ]
