# Generated by Django 4.2.2 on 2023-09-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_alter_solicitacoes_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitação Criada'), (2, 'Aguardando Entregas'), (3, 'Concluída'), (4, 'Devolvida')]),
        ),
    ]
