# Generated by Django 4.0.6 on 2023-09-05 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_alter_solicitacoes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.IntegerField(choices=[('1', 'Solicitação Criada'), ('2', 'Aguardando Entregas'), ('3', 'Concluída'), ('4', 'Devolvida')]),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='tipo_projeto',
            field=models.IntegerField(choices=[('1', 'EFG'), ('2', 'COTEC'), ('3', 'CETT')]),
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_tarefa', models.DateField(default=django.utils.timezone.now)),
                ('prazo_entrega', models.DateField()),
                ('data_entrega', models.DateField()),
                ('descricao_tarefa', models.TextField()),
                ('descricao_entrega', models.TextField()),
                ('entregavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.entregaveis')),
            ],
            options={
                'db_table': 'tarefas',
            },
        ),
    ]
