# Generated by Django 4.0.6 on 2023-09-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0009_alter_tarefas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='status',
            field=models.IntegerField(choices=[('0', 'AGUARDANDO ENTREGAS'), ('1', 'EM REVISÃO'), ('2', 'ENTREGUE')], default='0'),
        ),
    ]
