# Generated by Django 4.0.6 on 2023-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0011_tarefas_titulo_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='titulo_tarefa',
            field=models.TextField(),
        ),
    ]
