# Generated by Django 4.0.6 on 2023-09-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacoes', '0013_tarefas_usuario_designou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='usuario_designou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_designou', to=settings.AUTH_USER_MODEL),
        ),
    ]
