# Generated by Django 4.0.6 on 2023-09-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0014_alter_tarefas_usuario_designou'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='prioridade',
            field=models.IntegerField(choices=[('1', 'NORMAL'), ('2', 'PRIORIDADE')], default=1),
        ),
    ]
