# Generated by Django 4.0.6 on 2023-09-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0015_tarefas_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
