# Generated by Django 4.0.6 on 2023-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0016_alter_tarefas_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaveis',
            name='status',
            field=models.IntegerField(choices=[('0', 'AGUARDANDO ENTREGAS'), ('1', 'EM APROVAÇÃO'), ('2', 'APROVADO PELO CLIENTE')], default=0),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.IntegerField(choices=[('1', 'Solicitação Criada'), ('2', 'Aguardando Entregas'), ('3', 'Concluída'), ('4', 'Devolvida')], default=1),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='prioridade',
            field=models.IntegerField(choices=[('1', 'NORMAL'), ('2', 'PRIORIDADE')], default=0),
        ),
    ]
