# Generated by Django 4.2.2 on 2023-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0017_alter_entregaveis_status_alter_solicitacoes_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaveis',
            name='status',
            field=models.IntegerField(choices=[('0', 'AGUARDANDO ENTREGAS'), ('1', 'EM APROVAÇÃO'), ('2', 'APROVADO PELO CLIENTE'), ('3', 'DEVOLVIDA')], default=0),
        ),
    ]
