# Generated by Django 4.0.6 on 2023-09-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0020_alter_entregaveis_status_alter_tarefas_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaveis',
            name='status',
            field=models.IntegerField(choices=[('0', 'AGUARDANDO ENTREGAS'), ('1', 'AGUARDANDO APROVAÇÃO DA COMUNICAÇÃO'), ('2', 'APROVADA PELA COMUNICAÇÃO, AGUARDANDO APROVAÇÃO DO SOLICITANTE'), ('3', 'DEVOLVIDO'), ('4', 'APROVADO PELO SOLICITANTE')], default=0),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.IntegerField(),
        ),
    ]
