# Generated by Django 4.0.6 on 2023-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0021_alter_entregaveis_status_alter_tarefas_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('complemento', models.CharField(default=False, max_length=255)),
                ('convenio', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'escolas',
            },
        ),
    ]
