# Generated by Django 4.0.6 on 2023-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0022_escolas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='tipo_projeto',
            field=models.IntegerField(choices=[('1', 'EFG'), ('2', 'COTEC'), ('3', 'CETT'), ('4', 'BASILEU')]),
        ),
    ]
