# Generated by Django 4.0.6 on 2023-09-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0023_alter_solicitacoes_tipo_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaveis',
            name='status',
            field=models.IntegerField(choices=[('0', 'AGUARDANDO ENTREGAS'), ('1', 'AGUARDANDO APROVAÇÃO DA COMUNICAÇÃO'), ('2', 'APROVADA PELA COMUNICAÇÃO, AGUARDANDO APROVAÇÃO DO SOLICITANTE'), ('3', 'DEVOLVIDO'), ('4', 'APROVADO PELO SOLICITANTE'), ('5', 'Devolvido p/ Solicitante'), ('6', 'Negado')], default=0),
        ),
    ]
