# Generated by Django 4.0.6 on 2023-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0024_alter_entregaveis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='arquivos',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='status',
            field=models.IntegerField(choices=[('0', 'AGUARDANDO ENTREGAS'), ('1', 'AGUARDANDO APROVAÇÃO DA COMUNICAÇÃO'), ('2', 'APROVADA PELA COMUNICAÇÃO, AGUARDANDO APROVAÇÃO DO SOLICITANTE'), ('3', 'DEVOLVIDO'), ('4', 'APROVADO PELO SOLICITANTE'), ('5', 'DEVOLVIDO P/ SOLICITANTE'), ('6', 'NEGADO')], default=0),
        ),
    ]
