# Generated by Django 4.0.6 on 2023-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0025_tarefas_arquivos_alter_entregaveis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='arquivos',
            field=models.TextField(),
        ),
    ]
