# Generated by Django 4.0.6 on 2023-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0026_alter_tarefas_arquivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaveis',
            name='status',
            field=models.IntegerField(blank=True, choices=[('0', 'AGUARDANDO ENTREGAS'), ('1', 'AGUARDANDO APROVAÇÃO DA COMUNICAÇÃO'), ('2', 'APROVADA PELA COMUNICAÇÃO, AGUARDANDO APROVAÇÃO DO SOLICITANTE'), ('3', 'DEVOLVIDO'), ('4', 'APROVADO PELO SOLICITANTE'), ('5', 'DEVOLVIDO P/ SOLICITANTE'), ('6', 'NEGADO')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='tipo_entregavel',
            field=models.IntegerField(blank=True, choices=[('1', 'SAVE THE DATE'), ('2', 'DIVULGAÇÃO'), ('3', 'PROGRAMAÇÃO'), ('4', 'STAND')], null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='tipo_produto',
            field=models.IntegerField(blank=True, choices=[('1', 'DIGITAL'), ('2', 'IMPRESSO'), ('3', 'AUDIOVISUAL'), ('4', 'COBERTURA DE EVENTO'), ('5', 'PRODUÇÃO (ORÇAMENTOS E EXECUÇÕES)'), ('6', 'IDENTIDADE VISUAL'), ('7', 'PLANEJAMENTO'), ('8', 'BRINDES'), ('9', 'COMUNICAÇÃO VISUAL')], null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao_entrega',
            field=models.TextField(null=True),
        ),
    ]
