# Generated by Django 4.0.6 on 2023-09-14 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacoes', '0027_alter_entregaveis_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaveis',
            name='categoria_produto',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='data_solicitacao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='descricao_audio_visual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes'),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='exemplo_arte',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='motivo_revisao',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='cep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='convenio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programacao_adicional',
            name='atividade',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programacao_adicional',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programacao_adicional',
            name='hora',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='programacao_adicional',
            name='hora_final',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='programacao_adicional',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes'),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='data_solicitacao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='evento_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='motivo_alteracao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='publico_evento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='arquivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_tarefa',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao_tarefa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='entregavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.entregaveis'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='titulo_tarefa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='usuario_designou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_designou', to=settings.AUTH_USER_MODEL),
        ),
    ]
