# Generated by Django 4.0.6 on 2023-09-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0028_alter_entregaveis_categoria_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaveis',
            name='tipo_produto',
            field=models.IntegerField(blank=True, choices=[('1', 'DIGITAL'), ('2', 'IMPRESSO'), ('3', 'AUDIOVISUAL'), ('4', 'COBERTURA DE EVENTO'), ('5', 'PRODUÇÃO (ORÇAMENTOS E EXECUÇÕES)'), ('6', 'IDENTIDADE VISUAL'), ('7', 'PLANEJAMENTO'), ('8', 'BRINDES'), ('9', 'COMUNICAÇÃO VISUAL')], default=5, null=True),
        ),
    ]
