# Generated by Django 4.0.6 on 2023-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0029_alter_entregaveis_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaveis',
            name='descricao_audio_visual',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
