# Generated by Django 4.0.6 on 2023-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0030_alter_entregaveis_descricao_audio_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
