# Generated by Django 4.0.6 on 2023-10-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0031_solicitacoes_prazo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='briefing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregaveis',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregaveis', to='solicitacoes.solicitacoes'),
        ),
        migrations.AlterField(
            model_name='programacao_adicional',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programacao_adicional', to='solicitacoes.solicitacoes'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='entregavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='solicitacoes.entregaveis'),
        ),
    ]
