# Generated by Django 3.2.21 on 2023-10-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0032_auto_20231011_1046'),
        ('solicitacoes', '0032_solicitacoes_briefing_alter_entregaveis_evento_and_more'),
    ]

    operations = [
    ]
