# Generated by Django 4.0.6 on 2023-10-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0033_solicitacoes_arquivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaveis',
            name='arquivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
