# Generated by Django 4.0.6 on 2023-11-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0034_entregaveis_arquivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaveis',
            name='outros',
            field=models.TextField(blank=True, null=True),
        ),
    ]
