# Generated by Django 3.2.21 on 2023-10-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0033_merge_20231011_1625'),
        ('solicitacoes', '0034_entregaveis_arquivos'),
    ]

    operations = [
    ]
