# Generated by Django 4.0.6 on 2023-11-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0035_entregaveis_outros'),
        ('solicitacoes', '0035_merge_20231027_1426'),
    ]

    operations = [
    ]
