# Generated by Django 3.2.21 on 2023-11-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0035_entregaveis_outros'),
        ('solicitacoes', '0035_merge_20231027_1426'),
    ]

    operations = [
    ]
