# Generated by Django 4.0.6 on 2023-09-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitacoes', '0023_alter_solicitacoes_tipo_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permissao', models.TextField(default='')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.escolas')),
            ],
            options={
                'db_table': 'permissoes',
            },
        ),
    ]
