# Generated by Django 4.0.6 on 2023-09-11 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerir_time', '0002_permissoes_usuario_alter_permissoes_permissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissoes',
            name='permissao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='permissoes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
