# Generated by Django 4.0.6 on 2023-09-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerir_time', '0003_alter_permissoes_permissao_alter_permissoes_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.TextField()),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
    ]
