# Generated by Django 4.0.6 on 2023-09-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerir_time', '0004_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissoes',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerir_time.departamentos'),
        ),
    ]
