# Generated by Django 4.0.6 on 2023-09-14 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0028_alter_entregaveis_categoria_produto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerir_time', '0006_alter_permissoes_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='departamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permissoes',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerir_time.departamentos'),
        ),
        migrations.AlterField(
            model_name='permissoes',
            name='permissao',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='permissoes',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.escolas'),
        ),
        migrations.AlterField(
            model_name='permissoes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
